name: CI Builds

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Maven Verify
        run: |
          ./mvnw --batch-mode --no-transfer-progress -B verify

      - name: E2E Tests
        run: |
          EXPECTED_RESULT="Hello world"
          URL="http://localhost:8080/hello"

          ./mvnw --batch-mode --no-transfer-progress -B compile exec:java -Dexec.mainClass="com.mycompany.app.Main" -pl myServlet1 &
          sleep 10
          RESPONSE=$(curl -s "$URL")
          if [ "$RESPONSE" = "$EXPECTED_RESULT" ]; then
              echo "OK"
          else
              echo "KO"
          fi
          kill $(lsof -t -i:8080)

          ./mvnw --batch-mode --no-transfer-progress -B compile exec:java -Dexec.mainClass="com.mycompany.app.Main" -pl myServlet2 &
          sleep 10
          RESPONSE=$(curl -s "$URL")
          if [ "$RESPONSE" = "$EXPECTED_RESULT" ]; then
              echo "OK"
          else
              echo "KO"
          fi
          kill $(lsof -t -i:8080)

          ./mvnw --batch-mode --no-transfer-progress -B compile exec:java -Dexec.mainClass="com.mycompany.app.Main" -pl myServlet3 &
          sleep 10
          RESPONSE=$(curl -s "$URL")
          if [ "$RESPONSE" = "$EXPECTED_RESULT" ]; then
              echo "OK"
          else
              echo "KO"
          fi
          kill $(lsof -t -i:8080)