name: CI Builds

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Maven Verify
        run: |
          make project-verify

      - name: E2E Tests
        run: |
          EXPECTED_RESULT="Hello world"
          URL="http://localhost:8080/hello"

          function run_test {
              MAKE_RECIPE=$1
              echo "Running test for make $MAKE_RECIPE..."
              
              make "$MAKE_RECIPE" &
              sleep 10
              RESPONSE=$(curl -s "$URL")
              
              if [ "$RESPONSE" = "$EXPECTED_RESULT" ]; then
                  echo "OK"
              else
                  echo "KO"
              fi
              
              kill $(lsof -t -i:8080)
          }

          run_test "servlet"
          run_test "spring-framework-mvc"
          run_test "spring-framework-mvcfn"
          run_test "spring-boot-1"
          run_test "spring-boot-2"
          run_test "spring-boot-3"
          run_test "spring-boot-4"
          run_test "spring-boot-5"
          run_test "spring-boot-6"
          run_test "spring-boot-7"
          run_test "spring-boot-8"
          run_test "spring-boot-9"
          run_test "spring-boot-10"
          run_test "spring-boot-11"
          run_test "spring-boot-12"
          run_test "spring-boot-13"
          run_test "spring-boot-14"
          run_test "spring-boot-15"